CREATE TABLE [dbo].[schema_migrations]
(
	[version] NVARCHAR(4000) NOT NULL 
	, CONSTRAINT [PK_schema_migrations] PRIMARY KEY CLUSTERED ([version])
);
GO

EXEC sys.sp_addextendedproperty
	@name = N'MS_Description'
	, @value = N'Table generated by Ruby'
	, @level0type = N'SCHEMA'
	, @level0name = N'dbo'
	, @level1type = N'TABLE'
	, @level1name = N'schema_migrations';
GO